module.exports = {
    clear: "\x1b[0m",
    s: {
        normal: "\x1b[0m",
        blob: "\x1b[1m",
        vague: "\x1b[2m",
        italic: "\x1b[3m",
        underline: "\x1b[4m",
        blink: "\x1b[5m",
        fblink: "\x1b[6m",
        inverse: "\x1b[7m",
        hide: "\x1b[8m",
    },
    f: {
        gray: "\x1b[30m",
        red: "\x1b[31m",
        green: "\x1b[32m",
        yellow: "\x1b[33m",
        blue: "\x1b[34m",
        magenta: "\x1b[35m",
        cyan: "\x1b[36m",
        white: "\x1b[37m",
    },
    b: {
        gray: "\x1b[40m",
        red: "\x1b[41m",
        green: "\x1b[42m",
        yellow: "\x1b[43m",
        blue: "\x1b[44m",
        magenta: "\x1b[45m",
        cyan: "\x1b[46m",
        white: "\x1b[47m",
    },
    gray: "\x1b[30m",
    red: "\x1b[31m",
    green: "\x1b[32m",
    yellow: "\x1b[33m",
    blue: "\x1b[34m",
    magenta: "\x1b[35m",
    cyan: "\x1b[36m",
    white: "\x1b[37m",
}